#!/usr/bin/env bash
#
# update-index.sh — Regenerate the PROJECT_INDEX.md from GitHub API data
#
# This script queries GitHub for all repos in the mojomast org,
# matches them against the submodule list, and regenerates the
# project index with fresh descriptions and metadata.
#
# Usage:
#   ./scripts/update-index.sh
#
set -euo pipefail

MONOREPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GITHUB_ORG="mojomast"

echo "🐙 Regenerating PROJECT_INDEX.md..."

cd "${MONOREPO_ROOT}"

# Get list of active submodules
SUBMODULES=$(git submodule status | awk '{print $2}')

# Fetch repo data from GitHub
echo "📡 Fetching repo data from GitHub..."
REPOS_JSON=$(gh repo list "${GITHUB_ORG}" --limit 200 --json name,description,primaryLanguage,url,isPrivate 2>/dev/null)

# Build the index
INDEX_FILE="${MONOREPO_ROOT}/docs/PROJECT_INDEX.md"

cat > "${INDEX_FILE}" << 'HEADER'
# 📋 Ussyverse Project Index

> Auto-generated by `scripts/update-index.sh` — last updated: PLACEHOLDER_DATE

## Overview

PLACEHOLDER_STATS

HEADER

# Replace date
sed -i "s/PLACEHOLDER_DATE/$(date -u +%Y-%m-%d)/" "${INDEX_FILE}"

# Process each category
CATEGORIES=(ai-agents chat-bots code-analysis creative data-science dev-tools games infra media security web-apps)
CATEGORY_EMOJIS=(🤖 💬 🔍 🎨 📊 🛠️ 🎮 🏗️ 🎬 🔒 🌐)
CATEGORY_NAMES=("AI Agents" "Chat Bots" "Code Analysis" "Creative" "Data Science" "Dev Tools" "Games" "Infrastructure" "Media" "Security" "Web Apps")

total=0

for i in "${!CATEGORIES[@]}"; do
    cat="${CATEGORIES[$i]}"
    emoji="${CATEGORY_EMOJIS[$i]}"
    name="${CATEGORY_NAMES[$i]}"
    
    # Find submodules in this category
    cat_projects=$(echo "${SUBMODULES}" | grep "^projects/${cat}/" | sed "s|projects/${cat}/||" | sort)
    
    if [[ -z "${cat_projects}" ]]; then
        continue
    fi
    
    count=$(echo "${cat_projects}" | wc -l)
    total=$((total + count))
    
    {
        echo ""
        echo "---"
        echo ""
        echo "## ${emoji} ${name} (${count})"
        echo ""
        echo "| # | Project | Language | Description | Status |"
        echo "|---|---------|----------|-------------|--------|"
        
        num=1
        while IFS= read -r proj; do
            # Get repo info from GitHub data
            lang=$(echo "${REPOS_JSON}" | python3 -c "
import json, sys
data = json.load(sys.stdin)
for r in data:
    if r['name'] == '${proj}':
        l = r.get('primaryLanguage', {})
        print(l.get('name', '—') if l else '—')
        break
" 2>/dev/null || echo "—")
            
            desc=$(echo "${REPOS_JSON}" | python3 -c "
import json, sys
data = json.load(sys.stdin)
for r in data:
    if r['name'] == '${proj}':
        print((r.get('description') or '—')[:70])
        break
" 2>/dev/null || echo "—")
            
            priv=$(echo "${REPOS_JSON}" | python3 -c "
import json, sys
data = json.load(sys.stdin)
for r in data:
    if r['name'] == '${proj}':
        print('🔒' if r.get('isPrivate') else '🟢')
        break
" 2>/dev/null || echo "🟡")
            
            echo "| ${num} | [${proj}](https://github.com/${GITHUB_ORG}/${proj}) | ${lang} | ${desc} | ${priv} |"
            num=$((num + 1))
        done <<< "${cat_projects}"
    } >> "${INDEX_FILE}"
done

# Add stats header
sed -i "s/PLACEHOLDER_STATS/Total: **${total}** projects across **${#CATEGORIES[@]}** categories/" "${INDEX_FILE}"

# Add alphabetical index
{
    echo ""
    echo "---"
    echo ""
    echo "## 🔤 Alphabetical Index"
    echo ""
    echo "| Project | Category | Language |"
    echo "|---------|----------|----------|"
    
    # Collect all projects with their categories
    for i in "${!CATEGORIES[@]}"; do
        cat="${CATEGORIES[$i]}"
        cat_projects=$(echo "${SUBMODULES}" | grep "^projects/${cat}/" | sed "s|projects/${cat}/||")
        while IFS= read -r proj; do
            [[ -z "${proj}" ]] && continue
            lang=$(echo "${REPOS_JSON}" | python3 -c "
import json, sys
data = json.load(sys.stdin)
for r in data:
    if r['name'] == '${proj}':
        l = r.get('primaryLanguage', {})
        print(l.get('name', '—') if l else '—')
        break
" 2>/dev/null || echo "—")
            echo "| [${proj}](https://github.com/${GITHUB_ORG}/${proj}) | ${cat} | ${lang} |"
        done <<< "${cat_projects}"
    done | sort -t'|' -k2
} >> "${INDEX_FILE}"

echo ""
echo "✅ PROJECT_INDEX.md regenerated with ${total} projects"
echo "📝 Review the changes and commit: git add docs/PROJECT_INDEX.md && git commit -m 'docs: update project index'"
